theme: jekyll-theme-cayman
repository: robaso-strikes-back/RobasoStrikesBack
author:
  name: Daniel Heinrich 
  url: https://github.com/Danny02
plugins:
  - jekyll-feed
  - jekyll-paginate

paginate: 3

